
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2007:Do not directly await a Task without calling ConfigureAwait", Justification = "<Pending>", Scope = "member", Target = "~M:Exercise3.UWP.Activation.ActivationHandler`1.HandleAsync(System.Object)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2007:Do not directly await a Task without calling ConfigureAwait", Justification = "<Pending>", Scope = "member", Target = "~M:Exercise3.UWP.Activation.DefaultLaunchActivationHandler.HandleInternalAsync(Windows.ApplicationModel.Activation.LaunchActivatedEventArgs)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2007:Do not directly await a Task without calling ConfigureAwait", Justification = "<Pending>", Scope = "member", Target = "~M:Exercise3.UWP.App.OnActivated(Windows.ApplicationModel.Activation.IActivatedEventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2007:Do not directly await a Task without calling ConfigureAwait", Justification = "<Pending>", Scope = "member", Target = "~M:Exercise3.UWP.App.OnLaunched(Windows.ApplicationModel.Activation.LaunchActivatedEventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2007:Do not directly await a Task without calling ConfigureAwait", Justification = "<Pending>", Scope = "member", Target = "~M:Exercise3.UWP.Services.ActivationService.ActivateAsync(System.Object)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1822:Member GetActivationHandlers does not access instance data and can be marked as static (Shared in VisualBasic)", Justification = "<Pending>", Scope = "member", Target = "~M:Exercise3.UWP.Services.ActivationService.GetActivationHandlers~System.Collections.Generic.IEnumerable{Exercise3.UWP.Activation.ActivationHandler}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1822:Member InitializeAsync does not access instance data and can be marked as static (Shared in VisualBasic)", Justification = "<Pending>", Scope = "member", Target = "~M:Exercise3.UWP.Services.ActivationService.InitializeAsync~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2007:Do not directly await a Task without calling ConfigureAwait", Justification = "<Pending>", Scope = "member", Target = "~M:Exercise3.UWP.Services.ActivationService.InitializeAsync~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1822:Member IsInteractive does not access instance data and can be marked as static (Shared in VisualBasic)", Justification = "<Pending>", Scope = "member", Target = "~M:Exercise3.UWP.Services.ActivationService.IsInteractive(System.Object)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1822:Member StartupAsync does not access instance data and can be marked as static (Shared in VisualBasic)", Justification = "<Pending>", Scope = "member", Target = "~M:Exercise3.UWP.Services.ActivationService.StartupAsync~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2007:Do not directly await a Task without calling ConfigureAwait", Justification = "<Pending>", Scope = "member", Target = "~M:Exercise3.UWP.Services.ActivationService.StartupAsync~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2227:Change 'Items' to be read-only by removing the property setter.", Justification = "<Pending>", Scope = "member", Target = "~P:Exercise3.UWP.Models.DragDropStartingData.Items")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1052:Type 'DragDropService' is a static holder type but is neither static nor NotInheritable", Justification = "<Pending>", Scope = "type", Target = "~T:Exercise3.UWP.Services.DragAndDrop.DragDropService")]